### PR TITLE
Option to generate shared library & use GNUInstallDirs on linux

### PR DESCRIPTION
**Pull request by jonathanspw**
I think this will take care of #75.  Please test on windows/apple if you can - i tested the new option on linux and it works well.

Windows/apple change slightly just due to adding GNUInstallDirs and compatible variables for win/apple.

You'll probably want to change the way versioning is handled in CMakeLists.txt line 2 long term.

This causes the shared lib to be versioned based on the major version number (ie 1 here) so if the ABI changes you'll probably want to increment major versions.

### CODE REVIEW

**Comment by btzy** [comment]
Thanks, I'll take a look.  I'm also going to temporary push a commit onto your branch to add shared library builds to the CI, just to check them.

**Comment by btzy** [comment]
I modified it to use GNUInstallDirs on all OSes, which seems to be the more correct thing to do (and it can be overriden by CMAKE_INSTALL_PREFIX.  SFML seems to do this https://github.com/SFML/SFML/pull/1576.

**Comment by btzy** [comment]
I'm willing to accept this PR as it currently is, but we probably need to figure out changing the name of the GTK/portal builds if that is desired.

**Comment by jonathanspw** [comment]
This is ready to merge.

**Pull request merged**
